# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.locales: [en,fr,de]
    picto_directory: '%kernel.project_dir%/public/uploads/picto_directory'
    picture_directory: '%kernel.project_dir%/public/uploads/picture_directory'
    images_directory: '%kernel.project_dir%/public/uploads/product_directory'
    documents_directory: '%kernel.project_dir%/public/uploads/documents_directory'
    employee_documents_directory: '%kernel.project_dir%/public/uploads/employee_documents_directory'
    sale_documents_directory: '%kernel.project_dir%/public/uploads/sale_documents_directory'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
